name: publish-package
on:
  release:
    types:
      - published
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - id: install_dependencies
        run: yarn install
      - id: build_package
        run: yarn build
      - id: publish && cp package.json dist/package.json && cp yarn.lock dist/yarn.lock
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> dist/.npmrc
      - run: cd dist && npm publish