name: tests
on:
  pull_request:
    branches:
      - staging
    types: [closed]
jobs:
  run-tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo ADD TESTS!!
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - id: version
        run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - id: build_package
        run: yarn install
      - run: yarn build
      - run: cp ./package.json ./dist/package.json
      - run: cp ./yarn.lock ./dist/yarn.lock
      - id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ fromJson(steps.version.outputs.packageJSON).version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}