name: version-control
on:
  pull_request:
    branches:
      - staging
env:
  URL: https://registry.npmjs.org/your-http
jobs:
  kakanica:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_code_version
        run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - id: get_npm_package_version
        run: |
          content=`curl -X GET $URL`
          echo "::set-output name=response::$content"
      - id: compare
        if: ${{ fromJson(steps.get_code_version.outputs.packageJson).version == fromJson(steps.get_npm_package_version.outputs.response).versions[fromJson(steps.get_code_version.outputs.packageJson).version].version }}
        run: exit 69