name: version-control
on:
  pull_request:
    branches:
      - staging
    types: [closed]
jobs:
  check-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: actions/checkout@v1
      - uses: nyaa8/package-version@v1
      - id: package_version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: your-http
      - if: ${{ steps.package-version.outputs.current-version == env.PACKAGE_VERSION }}
        run: exit 1