name: version-control
on:
  pull_request:
    branches:
      - staging
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: technote-space/package-version-check-action@v1
        with:
          BRANCH_PREFIX: staging/
          