name: version-control
on:
  pull_request:
    branches:
      - staging
jobs:
  check-version:
    runs_on: ubuntu_latest
    steps:
      - id: version
      - uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - id: package_version
      - uses: martinbeentjes/npm-get-version-action@master
        with:
          path: package/your-http
      if: ${{ steps.package-version.outputs.current-version == steps.format_script.outputs.prop }}
          run: exit 1